### PR TITLE
Refactor dev branch with Python package structure

### PR DESCRIPTION
**Pull request by mmorys**
First, thanks for the great work on this. In order to make full use of Ryven for my application, I needed to be able to easily pip install ryven. I did basic refactoring of your latest dev branch into a traditional Python package format, with a directory structure:

```
Ryven/
├─ docs/
├─ ryven/
│  ├─ core/
│  │  ├─ <files that I thought are needed for basic Ryven operation>
│  ├─ gui/
│  │  ├─ <files related to the GUI execution>
│  ├─ packages/
│  ├─ resources/
│  ├─ saves/
│  ├─ stuff/
├─ setup.py
├─ setup.cfg
├─ <other top level files>
```

I didn't make any functional changes to the code. In order to have everything still function and import properly, I changed all local relative imports to absolute imports (e.g. `from NENV import *` becomes `from ryven.core.NENV import *`.)

If you find this useful, feel free to pull it, or if not, I'll just continue using it from my own fork.

Best,
Marcin

### CODE REVIEW

**Comment by mmorys** [comment]
1. That can be changed to anything you feel is appropriate. I've seen `core` used in many other projects, but maybe `main` or `shared` would be better.
2. I don't see a problem with it, and it wouldn't cause any issues. If it's important for the user to read, maybe it could be moved into the `docs` directory instead. I've used [Sphinx](https://www.sphinx-doc.org/en/master/) in the past to make documentation, and was able to add links in the Markdown files in `docs` pointing to files elsewhere. You could link to these readmes so they're visible in the docs as well?
3. Yes, both work. In `setup.cfg` I have added entrypoints, which map the command `ryven` to the main function in `Ryven.py`.
4. Correct, those should be outside the package directory. I think it's fairly common for packages to use a directory in the user's home, like `~/.ryven/`. I think that having some fundamental nodes packaged with `ryven` would be fine, but sourcing from another location for additional files would be a good idea. In the future (probably a different pull request) we could implement a plugin system for nodes. That would allow someone to write a new package containing nodes and have them register themselves with Ryven.

**Comment by mmorys** [comment]
5. You have another repo for the [website](https://github.com/leon-thomm/ryven-website). Do the `docs` in the Ryven repo get used/linked in the website, or are they simply viewed on the github page?
6. Before publishing to PyPI there are some files that probably need to be cleaned up. I tried not to change anything in this PR, so you could potentially pull this in and start your own branch to clean up as you see fit. I don't know if you want to keep those *.bat files at the top level, for instance.

**Comment by leon-thomm** [comment]
1. Especially `from ryven.core. ... import ...` might cause confusion, `main` might be better (I would then move `Ryven.py` there too). The reason I placed `NENV.py` and `NWENV.py` in the top-level package is that node files are then unaffected by such changes, and I'd say `from ryven.NENV import *` is more intuitive **(see changes below)**
2. Yes, I think that would be neat.
3. nice.
4. Importing node packages as well as loading projects should then somehow have an option `import example nodes` resp. `load example project` **(see changes below)**
5. The `docs` folder also includes [node tutorials](https://github.com/mmorys/Ryven/tree/dev-package/docs/node%20tutorials), the rest was used for the introductory guide which is now indeed part of the website repo and therefore useless here. **(see changes below)**
6. Yes, clean up is on my todo, including some refactoring of folders and files. The batch files I will probably exclude (I need them for development, but they don't have to be part of the repo). But this kind of cleaning I think I will do once the PR is merged, as it is not directly related to the new package structure.

I just cloned your fork and worked on the points above, in particular
- I added the necessary path utils for `example_projects`, `example_nodes`, `~/.ryven/saves/ ` and `~/.ryven/nodes/` and the options to load from example directories; and extended auto import
- I moved `NENV.py` and `NWENV.py` to `Ryven/ryven/` to enable `from ryven.NENV import *` syntax
- I renamed `core/` to `main/`, and moved `Ryven.py` into `main/`
- cleaned the `docs` folder
- and I did some renaming of stuff somehow related to this PR's project structure

If you agree with those changes and give me write access, I can commit to the PR.

**Comment by mmorys** [comment]
I have "allow edits by maintainers" checked, so you should have write permissions to the branch.

Instead of moving content (i.e. `NENV.py`) to the top level of `ryven`, I would suggest importing any functions you want accessible from the top level in the `__init__.py` file. For instance, to have `NENV` available, leave it in `ryven/main/NENV.py` and simply add `from .main import NENY` to the `ryven/__init__.py` file. Repeat for any other modules, classes, or functions you want available at the top level for convenience.

I also thought of another possible name, `common`, for the previous `core` directory. That would prevent possible confusion with the commonly used main() function.

**Comment by leon-thomm** [comment]
> I would suggest importing any functions you want accessible from the top level in the `__init__.py` file

yeah, that would be the cleaner approach, but I think I can't do it like this right now, or at least I don't know how. `NENV.py` imports different stuff based on whether Ryven or RyvenConsole is running. This determined through and environment variable `RYVEN_MODE`, which currently gets set in `Ryven.py` (I will likely change that; when installed as package, `Ryven.py` doesnt actually need to be able to start RyvenConsole at all, but it doesn't solve the problem). However, when running cmd `ryven` or `ryven_console` (thus importing the ryven package in python), the top-level `__init__.py` is the first scripts that's executed, so I cannot already import `NENV` there.

> I also thought of another possible name, common, for the previous core directory. That would prevent possible confusion with the commonly used main() function.

Nice suggestion, but I'm not sure about that, at least I can't imagine a scenario where someone would reference both am might confuse them, and  `common` sounds more like `utils` to me, which is I think not exactly accurate. Furthermore, the actual `main()` function would be part of the `main` directory, along with all *core* components to start the application that are not directly gui related. Why do you think it might be a problem?

**Comment by leon-thomm** [comment]
just pushed my changes so you have them; small remaining adjustments (location of `NENV`/`NWENV` and name of `main`) can be done easily

**Comment by mmorys** [comment]
Sorry for the radio silence the last 2 weeks. Had some other life events pull me away from work for a while. I'll continue work from your merged branch, and help where I can moving forward.

**Comment by leon-thomm** [comment]
Hey no worries! I hope you are doing well, and thanks a lot for the refactoring, this might become quite useful in the future.
I am currently experimenting a bit with some enhancements of ryvencore (looking towards Cython 👀) for which having ryven itself as a pypi package would also be nice.

**Pull request merged**
